name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-project:
    runs-on: ubuntu-latest

    env:
      # LLM / API Configuration
      GPT_MODEL_NAME: ${{ secrets.GPT_MODEL_NAME }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}

      # RAG / Vector Store Configuration
      FAISS_INDEX_PATH: ${{ secrets.FAISS_INDEX_PATH }}
      EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL }}

      # Chunking & Retrieval Parameters
      CHUNK_SIZE: ${{ secrets.CHUNK_SIZE }}
      CHUNK_OVERLAP: ${{ secrets.CHUNK_OVERLAP }}
      TOP_K_RESULTS: ${{ secrets.TOP_K_RESULTS }}

      # LLM Parameters
      TEMPRATURE: ${{ secrets.TEMPRATURE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run application
        run: |
          streamlit run .\main.py
